@echo off
setlocal EnableExtensions
cd /d "%~dp0"

echo.
echo === Sumo QR Scanner — build debug APK ===
echo.

REM --- Resolve PC LAN IP (first non-loopback IPv4) ---
set "LAN_IP="
for /f "tokens=2 delims=:" %%A in ('ipconfig ^| findstr /R /C:"IPv4 Address"') do (
  if not defined LAN_IP (
    for /f "tokens=* delims= " %%B in ("%%A") do set "LAN_IP=%%B"
  )
)

if not defined LAN_IP (
  echo Could not detect LAN IP. Edit local.properties manually.
  set "LAN_IP=192.168.0.1"
)

echo Detected LAN IP: %LAN_IP%
echo Default API URL will be: http://%LAN_IP%:5011
echo.

if exist "D:\android-build\sdk" (
  set "SDK_DIR=D:\\android-build\\sdk"
) else if exist "%LOCALAPPDATA%\Android\Sdk" (
  set "SDK_DIR=%LOCALAPPDATA:\=\\%\\Android\\Sdk"
) else (
  echo.
  echo Android SDK not found.
  echo Expected D:\android-build\sdk or %%LOCALAPPDATA%%\Android\Sdk
  echo.
  echo Options:
  echo   1^) Install Android Studio, open this folder, Sync, then re-run build-apk.bat
  echo   2^) Install Android SDK, then re-run this script.
  echo.
  exit /b 1
)

if exist "D:\android-build\jdk\jdk-17.0.20.1+1" (
  set "JAVA_HOME=D:\android-build\jdk\jdk-17.0.20.1+1"
)
if exist "D:\android-build\gradle-home" (
  set "GRADLE_USER_HOME=D:\android-build\gradle-home"
)

echo Writing local.properties
(
  echo ## Generated by build-apk.bat
  echo sdk.dir=%SDK_DIR%
  echo qr.api.base.url=http://%LAN_IP%:5011
) > local.properties

if not exist "gradlew.bat" (
  echo.
  echo Missing Gradle wrapper ^(gradlew.bat^).
  echo Open this folder once in Android Studio ^(File -^> Open^) so it generates the wrapper,
  echo then run build-apk.bat again.
  echo.
  echo.
  exit /b 1
)

echo Building...
call gradlew.bat :app:assembleDebug
if errorlevel 1 (
  echo Build failed.
  exit /b 1
)

echo.
echo APK ready:
echo   %cd%\app\build\outputs\apk\debug\app-debug.apk
echo.
echo Install on phone ^(USB debugging^):
echo   adb install -r app\build\outputs\apk\debug\app-debug.apk
echo.
echo Sign in the app to Espresso Backend ^(port 5011^).
echo.
endlocal
