#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"

echo ""
echo "=== Sumo QR Scanner — build debug APK ==="
echo ""

detect_lan_ip() {
  if command -v ip >/dev/null 2>&1; then
    ip -4 route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src"){print $(i+1); exit}}'
    return
  fi
  if command -v ipconfig.exe >/dev/null 2>&1; then
    ipconfig.exe | tr -d '\r' | awk '/IPv4 Address/{gsub(/.*: /,""); print; exit}'
    return
  fi
  echo "192.168.0.1"
}

LAN_IP="$(detect_lan_ip)"
LAN_IP="${LAN_IP:-192.168.0.1}"
BRIDGE_URL="http://${LAN_IP}:5055"

echo "Detected LAN IP: ${LAN_IP}"
echo "Bridge URL will be: ${BRIDGE_URL}"
echo ""

SDK_DIR="${ANDROID_SDK_ROOT:-${ANDROID_HOME:-${LOCALAPPDATA:-$HOME/AppData/Local}/Android/Sdk}}"

if [[ ! -f local.properties ]]; then
  echo "Creating local.properties..."
  # Escape backslashes for Windows sdk.dir
  SDK_ESC="${SDK_DIR//\\/\\\\}"
  cat > local.properties <<EOF
## Generated by build-apk.sh
sdk.dir=${SDK_ESC}
qr.bridge.base.url=${BRIDGE_URL}
qr.ingest.key=dev-qr-ingest-key
EOF
else
  echo "Updating qr.bridge.base.url in local.properties"
  if command -v sed >/dev/null 2>&1; then
    sed -i.bak -E "s|qr\\.bridge\\.base\\.url=.*|qr.bridge.base.url=${BRIDGE_URL}|" local.properties || true
  fi
fi

if [[ ! -d "$SDK_DIR" ]]; then
  echo ""
  echo "Android SDK not found at: $SDK_DIR"
  echo ""
  echo "Options:"
  echo "  1) Install Android Studio, open this folder, Sync, re-run ./build-apk.sh"
  echo "  2) No Studio: phone browser → ${BRIDGE_URL}/scan → Add to Home screen"
  echo ""
  exit 1
fi

if [[ ! -f ./gradlew ]]; then
  echo ""
  echo "Missing Gradle wrapper (./gradlew)."
  echo "Open this folder once in Android Studio so it generates the wrapper,"
  echo "then re-run ./build-apk.sh"
  echo ""
  echo "Or use the phone PWA: ${BRIDGE_URL}/scan → Add to Home screen"
  echo ""
  exit 1
fi

chmod +x ./gradlew
./gradlew :app:assembleDebug

APK="app/build/outputs/apk/debug/app-debug.apk"
echo ""
echo "APK ready: $(pwd)/${APK}"
echo "Install: adb install -r ${APK}"
echo "Keep qr-bridge running on the PC before scanning."
echo ""
